CREATE TABLE Renters
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	First NVARCHAR(100) NOT NULL,
	Last NVARCHAR(100) NULL,
);

CREATE TABLE RentPeriods
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Name NVARCHAR(40) NOT NULL,
	Month Date NOT NULL
);

CREATE TABLE Receipts
(
	Id UNIQUEIDENTIFIER PRIMARY KEY, 
	Name NVARCHAR(300) NOT NULL,
	Date DateTime NOT NULL,
	Tip decimal(18,4) NOT NULL,
	Tax decimal(18,4) NOT NULL,
	Total decimal(18,4) NOT NULL,
	Payer UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Renters(Id),
	RentId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES RentPeriods(Id)
);

CREATE TABLE Payments(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Payer UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Renters(Id),
	Payment decimal(18,4) NOT NULL,
	Tax decimal(18,4) NOT NULL,
	Tip decimal(18,4) NOT NULL,
	ReceiptId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Receipts(Id)
)